### ISSUE TITLE
Update Roundcube package to be compatible with privileged sandbox

### ISSUE THREAD

**Issue by paulproteus** [jparyani/roundcubemail#7]
In https://github.com/sandstorm-io/sandstorm/pull/2644 , Sandstorm got modified to support a mode of operation where the UID is not fixed.

In Kenton's manual testing so far, the only app affected by this is Roundcube.

I'm requesting a change to the Roundcube package where it can work properly independent of the UID that Sandstorm is running as.

**Comment by jparyani** [comment]
Fixed by 292d52257facab445cf4bd9202ccaf1de169a10c
